import type { Program } from '../omny/types'
import catalogJson from './glzCategories.json'

// Generated by scripts/catalog/build-mapping.py
interface GlzCatalog {
  // GLZ's site categories, in their menu order
  categories: string[]
  // Omny program ID -> GLZ category
  programCategories: Record<string, string>
  // Program path on the old GLZ site (what the old version of this app saved) -> Omny program ID
  legacyPaths: Record<string, string>
}

const catalog: GlzCatalog = catalogJson

const NETWORK_FALLBACK_GROUPS: Record<string, string> = {
  Galatz: 'עוד מגלי צה״ל',
  GLGLZ: 'עוד מגלגלצ',
  Podcasts: 'פודקאסטים',
}
const OTHER_GROUP = 'אחר'

export interface ProgramGroup {
  name: string
  programs: Program[]
}

// Must match normalize() in scripts/catalog/build-mapping.py
export function normalizeName(name: string): string {
  return name.toLowerCase().replace(/[^א-תa-z0-9]/g, '')
}

export function isListed(program: Program): boolean {
  return !program.Archived && !program.Hidden
}

function groupName(program: Program): string {
  return (
    catalog.programCategories[program.Id] ??
    (program.Network !== null ? NETWORK_FALLBACK_GROUPS[program.Network] : undefined) ??
    OTHER_GROUP
  )
}

export function groupPrograms(programs: Program[], search = ''): ProgramGroup[] {
  const query = search.trim().toLowerCase()
  const groups = new Map<string, Program[]>()

  for (const program of programs) {
    if (!isListed(program) || (query !== '' && !program.Name.toLowerCase().includes(query))) {
      continue
    }
    const name = groupName(program)
    groups.set(name, [...(groups.get(name) ?? []), program])
  }

  const order = [...catalog.categories, ...Object.values(NETWORK_FALLBACK_GROUPS), OTHER_GROUP]
  return order
    .filter((name) => groups.has(name))
    .map((name) => ({
      name,
      programs: (groups.get(name) ?? []).toSorted((a, b) => a.Name.localeCompare(b.Name, 'he')),
    }))
}

// Resolves a show path saved by the old version of the app to a current Omny program ID.
export function resolveLegacyPath(path: string, programs: Program[]): string | undefined {
  const knownIds = new Set(programs.map((program) => program.Id))
  const mapped = catalog.legacyPaths[path]
  if (mapped !== undefined && knownIds.has(mapped)) {
    return mapped
  }

  // Not in the menu snapshot; fall back to matching the slug against program names
  let slug = path.split('/').filter(Boolean).at(-1) ?? ''
  try {
    slug = decodeURIComponent(slug)
  } catch {
    // Already decoded and contains a stray '%'
  }
  const target = normalizeName(slug)
  if (target === '') {
    return undefined
  }

  const matches = programs.filter((program) => isListed(program) && normalizeName(program.Name) === target)
  return matches.length === 1 ? matches[0]?.Id : undefined
}
